name: ondoc_flutter_opentok
description: OpenTok Flutter - a library for OpenTok iOS and Android SDKs.
version: 0.0.10
homepage: https://github.com/ninjasolutions/ondoc_flutter_opentok

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.5.2
  json_serializable: ^3.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter_opentok
        pluginClass: FlutterOpentokPlugin
      ios:
        pluginClass: FlutterOpentokPlugin